version: '3.1'

services:
  db:
    image: postgres
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
#  arbeitszeit-backend:
#    build:
#      context: .
#      dockerfile: 'Dockerfile'
#    ports:
#      - '3030:3030'
#    environment:
#      DB_HOST: db
#      DB_PORT: 5432
#      DB_USERNAME: postgres
#      DB_PASSWORD: postgres
#      DB_NAME: postgres
